### ISSUE TITLE
Angular-webpack-starter-master/**.spec.ts' not found.

### ISSUE THREAD

**Issue by kawpii** [Bigless27/Angular-webpack-starter#2]
First of all thank you for the tutorial on Youtube. I found it really helpful.

npm run build-aot-prod give` Error File: /Angular-webpack-starter-master/**.spec.ts' not found.`

## Expected Behavior
build successfully using aot

## Current Behavior
`npm run build-aot-prod` give
```
Error File: /Angular-webpack-starter-master/**.spec.ts' not found.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lesson-on-coding-angular-webpack@1.0.0 build:aot: `ngc -p tsconfig-aot.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lesson-on-coding-angular-webpack@1.0.0 build:aot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kaushalya/.npm/_logs/2018-02-03T05_23_24_168Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lesson-on-coding-angular-webpack@1.0.0 build-aot-prod: `npm run build:aot && npm run webpack-prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lesson-on-coding-angular-webpack@1.0.0 build-aot-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kaushalya/.npm/_logs/2018-02-03T05_23_24_245Z-debug.log
```

## Possible Solution
Works when
in tsconfig-aot.js change
`"files": ["src/app/app.module.ts", "src/main.aot.ts", "**.spec.ts"],`
to
`"files": ["src/app/app.module.ts", "src/main.aot.ts"]`
 But since I think  **.spec.ts is for testing removing it is not an solution.

## Steps to Reproduce

1. clone the repository
2. npm install
3. npm run build-aot-prod

## Context (Environment)
Linux Mint 18.3

Please Help

**Comment by Bigless27** [comment]
Hey KaushalyaPradeep, sorry for getting back to you so late. I've been wayyyyyy to busy with code stuff lately! To answer your question the solution you have for removing the `"**.spec.ts"` from the files array is the correct solution. You do not want to include your tests in your prod bundle. They have no use being there and they add size to your bundle. Will push a fix in a second!

**Comment by Bigless27** [comment]
Hey KaushalyaPradeep . I apologize about gettin back to you so late. I've been dealing with a lottttttt of things lately. The solution you have of removing the `"**.spec.ts"` from the files array is the correct solution. You shouldn't include test's with your production bundle. The test have new use in production code and will only make your bundle size larger.
